maintainer       "Christoph Buente"
maintainer_email "cb@meinekleinefarm.org"
license          "All rights reserved"
description      "Deploys our mkf rails application to the server."
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"
depends          "rbenv"
depends          "application"
depends          "application_ruby"
depends          "application_nginx"
depends          "users"
